# Abuse YAML notation to make a heredoc. This will be ignored by the CI.
.__heredoc__: &__heredoc__
    - | 

        NOTE: INSTRUCTION HAVE BEEN MOVED TO ./dev/setup_secrets.sh
        This file should need minimal modification.

        Template for this files is from
        ~/misc/templates/PYPKG/.gitlab-ci.yml

        Enable the opencv-hack if needed, and turn on/off the desired versions
        of Python.

stages:
  - build
  - test
  - gpgsign
  - deploy


### TEMPLATES ###
# Define common templates using YAML anchors

.common_template: &common_template
    tags:
        # Tags define which runners will accept which jobs
        - docker
        - linux
        - build

    variables:
        # Change pip's cache directory to be inside the project directory since we can
        # only cache local items.
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/mb_work/cache_pip"


.build_template: &build_template
    # Tags define which runners will accept which jobs
    <<: 
        - *common_template

    stage: 
        build
    
    before_script:
        - python -V  # Print out python version for debugging

    script: 
        - python setup.py bdist_wheel --universal

    cache:
        paths:
            - .cache/pip

    artifacts:
        paths:
            - dist/*.whl


.test_full_template: &test_full_template
    # Tags define which runners will accept which jobs
    <<: 
        - *common_template

    stage: 
        test
    
    before_script:
        - python -V  # Print out python version for debugging
        - export PYVER=$(python -c "import sys; print('{}{}'.format(*sys.version_info[0:2]))")
        - pip install --progress-bar off virtualenv
        - virtualenv venv$PYVER
        - source venv$PYVER/bin/activate
        - pip install --progress-bar off pip -U
        - pip install --progress-bar off pip setuptools -U
        - python -V  # Print out python version for debugging
        - pip install --progress-bar off -r requirements.txt
        - pip install .

    script: 
        - ./run_tests.py

    cache:
        paths:
            - .cache/pip
            - venv/

    # Coverage is a regex that will parse the coverage from the test stdout
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


.__gpg_heredoc__: &__gpg_heredoc__
        - | 

            NOTE: THESE INSTRUCTION ARE BEING MOVED AND UPDATED IN THE DEV FOLDER


.gpgsign_template: &gpgsign_template
    <<: 
        - *common_template

    stage: 
        gpgsign

    script: 
        - export GPG_EXECUTABLE=gpg
        - export GPG_KEYID=$(cat dev/public_gpg_key)
        - echo "GPG_KEYID = $GPG_KEYID"
        - $GPG_EXECUTABLE --version
        - openssl version
        - $GPG_EXECUTABLE --list-keys
        - $GPG_EXECUTABLE --list-keys
        # Decrypt and import GPG Keys / trust
        # note the variable pointed to by VARNAME_CI_SECRET is a protected variables only available on master and release branch
        - source dev/secrets_configuration.sh
        - CI_SECRET=${!VARNAME_CI_SECRET}
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
        - $GPG_EXECUTABLE --list-keys  
        # The publish script only builds wheels and does gpg signing if TAG_AND_UPLOAD is False
        - pip install requests[security] twine 
        - MB_PYTHON_TAG=$MB_PYTHON_TAG DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE DEPLOY_BRANCH=release DO_TAG=False DO_UPLOAD=False ./publish.sh 

    artifacts:
        paths:
            - dist/*.asc
            - dist/*.tar.gz
            - dist/*.whl

    only:
        refs:
            # Gitlab will only expose protected variables on protected branches
            # (which I've set to be main, master, and release), so only run this stage
            # there.
            - master
            - main
            - release


.deploy_template: &deploy_template
    <<: 
        - *common_template

    stage: 
        deploy

    script: 
        - export GPG_EXECUTABLE=gpg
        - export GPG_KEYID=$(cat dev/public_gpg_key)
        - echo "GPG_KEYID = $GPG_KEYID"
        - $GPG_EXECUTABLE --version
        - openssl version
        - $GPG_EXECUTABLE --list-keys
        - $GPG_EXECUTABLE --list-keys
        # note the variable pointed to by VARNAME_CI_SECRET is a protected variables only available on master and release branch
        - source dev/secrets_configuration.sh
        - CI_SECRET=${!VARNAME_CI_SECRET}
        - PUSH_TOKEN=${!VARNAME_PUSH_TOKEN}
        - TWINE_PASSWORD=${!VARNAME_TWINE_PASSWORD}
        - TWINE_USERNAME=${!VARNAME_TWINE_USERNAME}
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
        - $GPG_EXECUTABLE --list-keys  
        # Install twine
        - pip install pyopenssl ndg-httpsclient pyasn1 -U 
        - pip install requests[security] twine 
        # Execute the publish script for real this time
        - TWINE_REPOSITORY_URL="https://upload.pypi.org/legacy/"
        - TWINE_REPOSITORY_URL=$TWINE_REPOSITORY_URL MB_PYTHON_TAG=$MB_PYTHON_TAG DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE CURRENT_BRANCH=release DEPLOY_BRANCH=release DO_TAG=True DO_UPLOAD=True ./publish.sh || echo "upload already exists"
        # do sed twice to handle the case of https clone with and without a read token
        - | 
            # Have the server git-tag the release and push the tags
            export VERSION=$(python -c "import setup; print(setup.VERSION)")
            # do sed twice to handle the case of https clone with and without a read token
            URL_HOST=$(git remote get-url origin | sed -e 's|https\?://.*@||g' | sed -e 's|https\?://||g' | sed -e 's|git@||g' | sed -e 's|:|/|g')
            echo "URL_HOST = $URL_HOST"
            # A git config user name and email is required. Set if needed.
            if [[ "$(git config user.email)" == "" ]]; then
                git config user.email "ci@gitlab.org.com"
                git config user.name "Gitlab-CI"
            fi
            TAG_NAME="v${VERSION}"
            echo "TAG_NAME = $TAG_NAME"
            if [ $(git tag -l "$TAG_NAME") ]; then
                echo "Tag already exists"
            else
                # if we messed up we can delete the tag
                # git push origin :refs/tags/$TAG_NAME
                # and then tag with -f
                git tag $TAG_NAME -m "tarball tag $VERSION"
                git push --tags "https://git-push-token:${PUSH_TOKEN}@${URL_HOST}"
            fi

            
    only:
        refs:
            - release


.build_install_test: &build_install_test
    - pip install -r requirements.txt -U


### JOBS ###
# Define the actual jobs

# ---------------
# Python 3.8 Jobs

build/cp38-cp38-linux:
    <<: 
        - *build_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8

test_full/cp38-cp38-linux:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8


# for universal builds we only need to gpg sign once
gpgsign/cp38-cp38-linux:
    <<: 
        - *gpgsign_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8

deploy/cp38-cp38-linux:
    <<: 
        - *deploy_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8


# ---------------
# Python 3.7 Jobs

build/cp37-cp37m-linux:
    <<: 
        - *build_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7

test_full/cp37-cp37m-linux:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7


# ---------------
# Python 3.6 Jobs

build/cp36-cp36m-linux:
    <<: 
        - *build_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6

test_full/cp36-cp36m-linux:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6

#gpgsign/cp36-cp36m-linux:
#    <<: 
#        - *gpgsign_template
#    image:
#        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6

#deploy/cp36-cp36m-linux:
#    <<: 
#        - *deploy_template
#    image:
#        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6

